server:
  port: 8088

logging:
  config: classpath:log/logback-spring.xml

spring:
  application:
    name: gray-server
  profiles:
    active: test

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.1.2:31848
        namespace: bd137bca-c91b-48c7-b6f5-51144333eea8
        username: nacos
      config:
        enabled: true
        server-addr: 192.168.1.2:31848
        namespace: bd137bca-c91b-48c7-b6f5-51144333eea8
        username: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8085
      log:
        dir: logs
dubbo:
  application:
    name: gray-server-dubbo
  registry:
    address: nacos://192.168.1.2:31848?namespace=bd137bca-c91b-48c7-b6f5-51144333eea8

feign:
  sentinel:
    enabled: true