server:
  port: 8081

logging:
  config: classpath:log/logback-spring.xml

spring:
  application:
    name: gray-server
  profiles:
    active: test

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.111.54.44:8848
        namespace: 90c2c745-53fb-43dd-898f-f6e311b2bfb7
        username: nacos
      config:
        enabled: true
        server-addr: 10.111.54.44:8848
        namespace: 90c2c745-53fb-43dd-898f-f6e311b2bfb7
        username: nacos
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8085
      log:
        dir: logs
dubbo:
  application:
    name: gray-server-dubbo
  registry:
    address: nacos://dev-nacos.fsk-internal.com:80?namespace=90c2c745-53fb-43dd-898f-f6e311b2bfb7

feign:
  sentinel:
    enabled: true